UPDATE storefront_products SET bc_url_slug = 'communication-cable-for-tigo-sol-ark-cat-5e-600v-90c-use-2-sunlight-resistant-ul-444' WHERE sku = 'CAT5E600V';
UPDATE storefront_products SET bc_url_slug = '545w-550w-bifacial-perc-monocrystalline-solar-panel-from-cw-energy' WHERE sku = 'CWT545WP';
UPDATE storefront_products SET bc_url_slug = 'rs-485-shielded-2-pair-24awg-communication-cable-for-tigo-sol-ark-modbus-canbus-ul-1685' WHERE sku = 'RS485COMS';
UPDATE storefront_products SET bc_url_slug = 'gripclip-wire-management' WHERE sku = 'GripClip';
UPDATE storefront_products SET bc_url_slug = 'deye-ge-f60-ip55-outdoor-61kwh' WHERE sku = 'DEYE- GE-F60';
UPDATE storefront_products SET bc_url_slug = '16-dc-brushless-snap-fan-12-24v-by-fogco' WHERE sku = 'SF.P16BLDC24';
UPDATE storefront_products SET bc_url_slug = 'tamarack-solar-flush-mount-rail-adapter' WHERE sku = '88436-8P';
UPDATE storefront_products SET bc_url_slug = '2-0-busbar-insulator-and-cover-with-5-wire-locations' WHERE sku = 'MNTBB2-BL';
UPDATE storefront_products SET bc_url_slug = 'rooftech-rt-mini-ii-self-flashing-roof-mount-base-deck-or-rafter-mount-two-in-one' WHERE sku = 'RT-MINI-8-SOLO';
UPDATE storefront_products SET bc_url_slug = 'genstar-mppt-charge-controller' WHERE sku = 'GS-MPPT-100M-200V';
UPDATE storefront_products SET bc_url_slug = '50-amp-300vdc-ground-fault-protector-din-rail-mount' WHERE sku = 'MNDC-GFP50-300';
UPDATE storefront_products SET bc_url_slug = 'tamarack-l-foot-with-rail-mount' WHERE sku = '88443-SOLO';
UPDATE storefront_products SET bc_url_slug = 'dc-thermostat-kit-by-fogco' WHERE sku = 'SF.9939';
UPDATE storefront_products SET bc_url_slug = 'mneacqzd' WHERE sku = 'MNEAC10QZD';
UPDATE storefront_products SET bc_url_slug = 's-5-edge-grab' WHERE sku = 'S-5 Edge Grab';
UPDATE storefront_products SET bc_url_slug = 'tigo-ts4-a-o' WHERE sku = '511-340112-2001';
UPDATE storefront_products SET bc_url_slug = '150vdc-din-rail-mount-breaker-non-polarized' WHERE sku = 'MNEPV1-150-1PNP';
UPDATE storefront_products SET bc_url_slug = 's-5-n-1-5' WHERE sku = 'S-5-N 1.5';
UPDATE storefront_products SET bc_url_slug = 'corrubracket-100t' WHERE sku = 'CorruBracket 100T';
UPDATE storefront_products SET bc_url_slug = '1-0-busbar-cover' WHERE sku = 'MN1/0LBBC-BLK (Long Black)';
UPDATE storefront_products SET bc_url_slug = '125vdc-panel-mount-breaker-3-8-studs-1-5' WHERE sku = 'MNEDC175';
UPDATE storefront_products SET bc_url_slug = 'kid-accessories' WHERE sku = 'MNKID-ASSY-KIT';
UPDATE storefront_products SET bc_url_slug = 'transfer-switch-for-the-big-baby' WHERE sku = 'MNTRANSFER-30A';
UPDATE storefront_products SET bc_url_slug = 'wire-management-tray-for-sol-ark' WHERE sku = 'SOL-ATR-15';
UPDATE storefront_products SET bc_url_slug = 'tamarack-uni-pgrm-top-of-pole-mount' WHERE sku = 'UNIPGRM-1P1';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-evault-max-18-5-kwh' WHERE sku = 'eVault Max';
UPDATE storefront_products SET bc_url_slug = '180-amp-busbar' WHERE sku = 'MNTBB-B';
UPDATE storefront_products SET bc_url_slug = 'renon-xtreme-home-battery-power-system' WHERE sku = 'REN-XTREME-NO-10';
UPDATE storefront_products SET bc_url_slug = 'burndy-bibs4-3-multiple-wire-terminal' WHERE sku = 'BIBS43';
UPDATE storefront_products SET bc_url_slug = '600v-10mm-x-38mm-fuses' WHERE sku = 'MN600FUSE-06';
UPDATE storefront_products SET bc_url_slug = 's-5-h90' WHERE sku = 'S-5-H90';
UPDATE storefront_products SET bc_url_slug = 'midnite-solar-mnedc175rt-remote-trip-175-amp-125vdc-panel-mount-breaker' WHERE sku = 'MIDMNEDC125RT';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-guardian-monitoring-tool' WHERE sku = 'Guardian';
UPDATE storefront_products SET bc_url_slug = 'roof-tech-deck-mount-screw' WHERE sku = 'RT-MINI-DMS';
UPDATE storefront_products SET bc_url_slug = 'pytes-v5-lifepo4-battery-pack' WHERE sku = '110000000000-A';
UPDATE storefront_products SET bc_url_slug = 'short-busbar' WHERE sku = 'MNSBB-BL';
UPDATE storefront_products SET bc_url_slug = 'tristar' WHERE sku = 'TS-30-NO';
UPDATE storefront_products SET bc_url_slug = 'powerfield-powerrack-ground-mount' WHERE sku = 'PowerRack-1000';
UPDATE storefront_products SET bc_url_slug = 'ryse-energy-air-wind-turbine' WHERE sku = '1-AR30-10-12';
UPDATE storefront_products SET bc_url_slug = 'small-solar-panels' WHERE sku = 'SOPA100W';
UPDATE storefront_products SET bc_url_slug = 'corrubracket' WHERE sku = 'CorruBracket';
UPDATE storefront_products SET bc_url_slug = 's-5-v' WHERE sku = 'S-5-V';
UPDATE storefront_products SET bc_url_slug = 'morningstar-suresine-inverter' WHERE sku = 'SI-1000-12-120-60-B';
UPDATE storefront_products SET bc_url_slug = '10-3-seoow-portable-cord-600v-ul-csa-power-cables' WHERE sku = 'SEOOW-CORD';
UPDATE storefront_products SET bc_url_slug = 'midnite-solar-surge-protector-device' WHERE sku = 'MNSPD-115';
UPDATE storefront_products SET bc_url_slug = 'tigo-ei-energy-intelligence-9-9kwh-battery' WHERE sku = 'TIGOBATT';
UPDATE storefront_products SET bc_url_slug = 'sci-powermount-pmr1-s' WHERE sku = '300-00';
UPDATE storefront_products SET bc_url_slug = 'rechargeable-aa-lithium-batteries-8-pack-with-charger' WHERE sku = 'EBL15VAA';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-eway-for-eboost-16kw' WHERE sku = 'eBoost eWay LITE';
UPDATE storefront_products SET bc_url_slug = '80-amp-150vdc-panel-mount-dc-ground-fault-protector' WHERE sku = 'MNDC-GFP80';
UPDATE storefront_products SET bc_url_slug = 'tamarack-pipe-kit-for-ttp-a-mounts' WHERE sku = 'PIPE-KIT-HW-10';
UPDATE storefront_products SET bc_url_slug = 's-5-t' WHERE sku = 'S-5-T';
UPDATE storefront_products SET bc_url_slug = 'hanger-bolt' WHERE sku = 'HANGER-BOLT-M10-1.5X200';
UPDATE storefront_products SET bc_url_slug = 'channel-end-clamp-8-pack' WHERE sku = '88467-8 pack';
UPDATE storefront_products SET bc_url_slug = 'solamp-trucker-cap' WHERE sku = 'TRUCKERHAT';
UPDATE storefront_products SET bc_url_slug = 'samlex-pst-inverter' WHERE sku = 'PST-1000-12';
UPDATE storefront_products SET bc_url_slug = 'deye-bos-g-ip-20-indoor-high-voltage-hv-batteries' WHERE sku = 'DEYE-BOS-G-40';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-envy-true-12kw-all-in-one-hybrid-inverter' WHERE sku = 'Envy12';
UPDATE storefront_products SET bc_url_slug = 'znshine-450w-bifacial-solar-panel' WHERE sku = 'ZXM7-SHLDD120';
UPDATE storefront_products SET bc_url_slug = 'midnite-solar-mnpowerflo5-battery' WHERE sku = 'MNPowerflo5';
UPDATE storefront_products SET bc_url_slug = 'tamarack-rectangular-base-flange' WHERE sku = '89785';
UPDATE storefront_products SET bc_url_slug = 'two-pole-din-rail-mount-120-240-vac-breaker' WHERE sku = 'MNEAC15-2P';
UPDATE storefront_products SET bc_url_slug = 'skystream-3-7-pro-ac-wind-turbine-w-mounting-pole-kit' WHERE sku = '1-S37M-240-60-2-US-KIT';
UPDATE storefront_products SET bc_url_slug = '1000v-10mm-x-38mm-fuses' WHERE sku = 'MN1000FUSE-01';
UPDATE storefront_products SET bc_url_slug = 'prostar-mppt-solar-charge-controller' WHERE sku = 'PS-MPPT-25';
UPDATE storefront_products SET bc_url_slug = 'rosie-pre-wired' WHERE sku = 'MNROSIEPW-16-KIT';
UPDATE storefront_products SET bc_url_slug = 'snap-fan-exhaust-shutter-system' WHERE sku = 'SFE.6900-12';
UPDATE storefront_products SET bc_url_slug = 'strain-relief' WHERE sku = 'GENSR-12';
UPDATE storefront_products SET bc_url_slug = 'kid-30amp-12v-24v-48v-controller' WHERE sku = 'MNKID-B';
UPDATE storefront_products SET bc_url_slug = 'skystream-3-7-marine-ac-wind-turbine' WHERE sku = '1-S37M-240-60-2-US';
UPDATE storefront_products SET bc_url_slug = 'morningstar-controller-accessories' WHERE sku = 'DIN-1';
UPDATE storefront_products SET bc_url_slug = 'ribbracket-iii' WHERE sku = 'RibBracket III';
UPDATE storefront_products SET bc_url_slug = 's-5-s' WHERE sku = 'S-5-S';
UPDATE storefront_products SET bc_url_slug = 'pgrm-component-parts' WHERE sku = '70-0300-PGM-B';
UPDATE storefront_products SET bc_url_slug = 'burndy-insulated-multitap-connector' WHERE sku = 'BIT04';
UPDATE storefront_products SET bc_url_slug = 'vsun-550w-vsun550-144bmh-dg' WHERE sku = 'VSUN550';
UPDATE storefront_products SET bc_url_slug = '80-volt-dc-breaker' WHERE sku = 'MNEPV100-80-1PNP';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-eforce-eway-base' WHERE sku = 'eForce eWay and Base';
UPDATE storefront_products SET bc_url_slug = 'din-rail-mount-277vac-triple-pole-breaker' WHERE sku = 'MNEAC30-3P';
UPDATE storefront_products SET bc_url_slug = 's-5-b-clamp' WHERE sku = 'S-5-B Clamp';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-eflex-max-5-4-kw' WHERE sku = 'FP-eflex MAX';
UPDATE storefront_products SET bc_url_slug = 'rosie' WHERE sku = 'MNE300ROSIE-240F';
UPDATE storefront_products SET bc_url_slug = 'single-arm-mounts' WHERE sku = 'UNI-SA/14.0';
UPDATE storefront_products SET bc_url_slug = '300-vdc-panel-mount-breaker' WHERE sku = 'MNEDC30-300';
UPDATE storefront_products SET bc_url_slug = 'tamarack-bulk-rails-ltl' WHERE sku = '88351';
UPDATE storefront_products SET bc_url_slug = '300vdc-din-rail-mount-breaker-polarized' WHERE sku = 'MNEPV-300-10';
UPDATE storefront_products SET bc_url_slug = 'sci-z-bracket' WHERE sku = '205-00';
UPDATE storefront_products SET bc_url_slug = 'busbar-insulator-and-cover-with-15-wire-locations' WHERE sku = 'MNTBB2-15-BL';
UPDATE storefront_products SET bc_url_slug = 's-5-z' WHERE sku = 'S-5-Z';
UPDATE storefront_products SET bc_url_slug = 'pure-copper-battery-cable-wire' WHERE sku = 'BATCABLE-10-12';
UPDATE storefront_products SET bc_url_slug = 'e-box-48100r-lifepo4-battery-pack' WHERE sku = 'E-Box-48100R';
UPDATE storefront_products SET bc_url_slug = 's-5-e-mini' WHERE sku = 'S-5-E-Mini';
UPDATE storefront_products SET bc_url_slug = 'solamp-power-circuit-tee' WHERE sku = '681D0D6D8168F_8855';
UPDATE storefront_products SET bc_url_slug = 'mini-dc-disconnect' WHERE sku = 'MNDC-C-SERIES';
UPDATE storefront_products SET bc_url_slug = 'midnite-solar-hawks-bay-breaker-box-125' WHERE sku = 'MNHAWKSBAYBB125';
UPDATE storefront_products SET bc_url_slug = 'tamarack-ttp-a-top-of-pole-mount' WHERE sku = 'TTP-A-2-93';
UPDATE storefront_products SET bc_url_slug = 'midnite-prewired-combiners' WHERE sku = 'MNPV2-MC4';
UPDATE storefront_products SET bc_url_slug = 'little-rosie-inverter' WHERE sku = 'MNLR3648M';
UPDATE storefront_products SET bc_url_slug = 'tamarack-2-in-pole-cap-with-u-bolts-box-of-2' WHERE sku = '`-90682';
UPDATE storefront_products SET bc_url_slug = 'sunstar-upright-refrigerator' WHERE sku = 'ST-10RF-B';
UPDATE storefront_products SET bc_url_slug = '20-hp-dc-brushless-snap-fan-24v-by-fogco' WHERE sku = 'SF.P20BLDC30';
UPDATE storefront_products SET bc_url_slug = 'sol-ark-hybrid-inverter' WHERE sku = 'SA-12K-2P';
UPDATE storefront_products SET bc_url_slug = 'sunlight-solar-charge-controller' WHERE sku = 'SL-10L-12V';
UPDATE storefront_products SET bc_url_slug = 'northstar-blue-vrla-agm-pure-lead-carbon-battery-183ah-12v-front-terminal' WHERE sku = 'NSB190FT-BLUEPLUS';
UPDATE storefront_products SET bc_url_slug = 's-5-s-mini' WHERE sku = 'S-5-S Mini';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-envy-8kw-10kw-all-in-one-hybrid-home-solar-inverter' WHERE sku = '8Envy';
UPDATE storefront_products SET bc_url_slug = 'sunstar-dc-chest-freezer' WHERE sku = 'ST-21CF';
UPDATE storefront_products SET bc_url_slug = 'tamarack-2-in-pipe-mount-with-u-bolt-8-pk' WHERE sku = '88955';
UPDATE storefront_products SET bc_url_slug = 'snap-fan-intake-guard-by-fogco' WHERE sku = 'SF.1222';
UPDATE storefront_products SET bc_url_slug = 's-5-n-mini' WHERE sku = 'S-5-N Mini';
UPDATE storefront_products SET bc_url_slug = 'rooftop-flush-mount-kits' WHERE sku = '90507';
UPDATE storefront_products SET bc_url_slug = 'bussmann-fusetron-dual-element-class-rk5-fuses' WHERE sku = '100AMP250VAC';
UPDATE storefront_products SET bc_url_slug = 'mamba-general-duty-junction-box' WHERE sku = 'MAMBA-442';
UPDATE storefront_products SET bc_url_slug = 'ground-or-roof-tilt-mounts' WHERE sku = 'UNI-GR/130';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-eforce-wallmount-bracket' WHERE sku = 'eForce Wallmount Bracket';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-solo-6-5kw-hybrid-inverter' WHERE sku = 'OffGrid 6500 Inverter';
UPDATE storefront_products SET bc_url_slug = 'tamarack-rail-splice' WHERE sku = '88375-SOLO';
UPDATE storefront_products SET bc_url_slug = 's-5-e' WHERE sku = 'S-5-E';
UPDATE storefront_products SET bc_url_slug = 'titan-mini-portable-solar-battery-pack' WHERE sku = 'titan-mini';
UPDATE storefront_products SET bc_url_slug = 'rail-tilt-kits-for-flat-and-low-slope-roofs' WHERE sku = 'UNI-TL1O';
UPDATE storefront_products SET bc_url_slug = 'snap-fan-solar-kit-by-fogco' WHERE sku = 'SF.9912BL';
UPDATE storefront_products SET bc_url_slug = '150vdc-panel-mount-breaker' WHERE sku = 'MNEDC10';
UPDATE storefront_products SET bc_url_slug = '16-amp-600-vdc-din-rail-mount-breaker' WHERE sku = 'MNEPV16-600RT';
UPDATE storefront_products SET bc_url_slug = 'tamarack-5050-clamp' WHERE sku = '88450-Solo';
UPDATE storefront_products SET bc_url_slug = 'solamp-stickers' WHERE sku = 'STICKER';
UPDATE storefront_products SET bc_url_slug = 'mneacqzd-2p' WHERE sku = 'MNEAC25QZD-2P';
UPDATE storefront_products SET bc_url_slug = 'distressed-dad-hat' WHERE sku = '66D65F1665890_10992';
UPDATE storefront_products SET bc_url_slug = 'rosie-pre-wired-system' WHERE sku = 'MNROSIEPW-16-KIT';
UPDATE storefront_products SET bc_url_slug = 'e-panel' WHERE sku = 'MNE300ROSIE-240F';
UPDATE storefront_products SET bc_url_slug = 'iota-engineering-dls-power-converter-and-battery-charger' WHERE sku = 'DLS-12V-75A/120V';
UPDATE storefront_products SET bc_url_slug = '2-0-busbar-insulator-and-cover-with-9-wire-locations' WHERE sku = 'MNTBB2-9 Blk';
UPDATE storefront_products SET bc_url_slug = 'tamarack-2-in-swivel-t-fitting-galv-steel' WHERE sku = '90699';
UPDATE storefront_products SET bc_url_slug = 'cableloc-wire-management' WHERE sku = 'CableLoc';
UPDATE storefront_products SET bc_url_slug = 'samlex-inverter-installation-kit' WHERE sku = 'DC-1000-KIT';
UPDATE storefront_products SET bc_url_slug = '80-or-100-amp-din-rail-mount-breaker' WHERE sku = 'MNEPV100';
UPDATE storefront_products SET bc_url_slug = 'mneac' WHERE sku = 'MNEAC10';
UPDATE storefront_products SET bc_url_slug = '300vdc-din-rail-mount-breaker-single-pole-polarized' WHERE sku = 'MNEPV10-300';
UPDATE storefront_products SET bc_url_slug = 's-5-mid-grab' WHERE sku = 'S-5 Mid Grab';
UPDATE storefront_products SET bc_url_slug = 's-5-z-mini' WHERE sku = 'S-5-Z Mini';
UPDATE storefront_products SET bc_url_slug = '20-dc-brushless-snap-fan-12-24v-by-fogco' WHERE sku = 'SF.P20BLDC24';
UPDATE storefront_products SET bc_url_slug = 'sci-powermount-900-s' WHERE sku = '210-00';
UPDATE storefront_products SET bc_url_slug = '300a-75mv-shunt-resistor' WHERE sku = 'SHUNT300A75MV';
UPDATE storefront_products SET bc_url_slug = 'battery-enclosures' WHERE sku = 'BATTERY ENCLOSUREKEY';
UPDATE storefront_products SET bc_url_slug = 'classic-mppt-charge-controller' WHERE sku = 'CLASSIC150';
UPDATE storefront_products SET bc_url_slug = 's-5-u-mini' WHERE sku = 'S-5-U Mini';
UPDATE storefront_products SET bc_url_slug = '63-amp-150vdc-din-rail-mount-dc-ground-fault-protector' WHERE sku = 'MNDC-GFP63';
UPDATE storefront_products SET bc_url_slug = '600vdc-din-rail-mount-two-pole-breaker' WHERE sku = 'MNEPV15-600-2PP';
UPDATE storefront_products SET bc_url_slug = 'versabracket-47' WHERE sku = 'VersaBracket 47';
UPDATE storefront_products SET bc_url_slug = 'small-breaker-boxes' WHERE sku = 'MNBABYBOX';
UPDATE storefront_products SET bc_url_slug = 'midnite-pv-combiners' WHERE sku = 'MNPV10-1000';
UPDATE storefront_products SET bc_url_slug = 'renon-xtreme-stack-battery-module' WHERE sku = 'XTREME-M-H';
UPDATE storefront_products SET bc_url_slug = '12-brushless-dc-snap-fan-12-24v-by-fogco' WHERE sku = 'SF.P12BLDC24';
UPDATE storefront_products SET bc_url_slug = 'fortress-power-envy-duo-21-inverter' WHERE sku = 'Envy-Duo-21';
UPDATE storefront_products SET bc_url_slug = 's-5-u' WHERE sku = 'S-5-U';
UPDATE storefront_products SET bc_url_slug = 's-5-n' WHERE sku = 'S-5-N';
UPDATE storefront_products SET bc_url_slug = 'ground-screw-foundations' WHERE sku = '91009';
UPDATE storefront_products SET bc_url_slug = '125vdc-panel-mount-breaker-width-1-inch-25-4mm-1-4-studs' WHERE sku = 'MNEDCRT-17';
UPDATE storefront_products SET bc_url_slug = 'kilovault-hlx-replacement-parts' WHERE sku = '320015008';
UPDATE storefront_products SET bc_url_slug = 'tamarack-ground-mount-kit' WHERE sku = '90798-A';
UPDATE storefront_products SET bc_url_slug = 'sol-ark-commercial-high-voltage-hybrid-inverters' WHERE sku = 'SA- 30K-3P-208V';
UPDATE storefront_products SET bc_url_slug = '410w-bifacial-perc-monocrystalline-solar-panel-from-cw-energy' WHERE sku = 'CWT410WP';
UPDATE storefront_products SET bc_url_slug = 'delta-lighting-arrestor' WHERE sku = 'CA302R';
