/**
 * Sync SEO data from solampio-migration to solampio-storefront
 *
 * Copies SEO fields generated by the batch optimizer from the migration DB
 * to the production storefront DB.
 *
 * Usage:
 *   npx tsx scripts/sync-seo-to-storefront.ts
 *   Add --dry-run to preview without making changes
 */

import { execSync } from 'child_process';
import * as fs from 'fs';

const SOURCE_DB = 'solampio-migration';
const TARGET_DB = 'solampio-storefront';
const DRY_RUN = process.argv.includes('--dry-run');
const LOG_FILE = './seo-storefront-sync.log';

interface SEOProduct {
  sku: string;
  seo_title: string | null;
  seo_meta_description: string | null;
  seo_og_title: string | null;
  seo_og_description: string | null;
  seo_keywords: string | null;
  seo_faqs: string | null;
  seo_use_cases: string | null;
  gmc_google_category: string | null;
  gmc_product_type: string | null;
  gmc_custom_label_0: string | null;
  gmc_custom_label_1: string | null;
  seo_last_optimized: string | null;
}

function log(message: string) {
  const timestamp = new Date().toISOString();
  const line = `[${timestamp}] ${message}`;
  console.log(line);
  fs.appendFileSync(LOG_FILE, line + '\n');
}

function queryD1(db: string, sql: string): any[] {
  const tmpFile = '/tmp/seo-sync-query.txt';
  fs.writeFileSync(tmpFile, sql);
  try {
    const result = execSync(
      `npx wrangler d1 execute ${db} --remote --json --command "$(cat ${tmpFile})"`,
      { encoding: 'utf-8', maxBuffer: 100 * 1024 * 1024, timeout: 120000 }
    );
    const parsed = JSON.parse(result);
    return parsed[0]?.results || [];
  } catch (error: any) {
    log(`D1 query failed: ${error.message}`);
    return [];
  }
}

function execD1(db: string, sql: string): boolean {
  const tmpFile = '/tmp/seo-sync-exec.txt';
  fs.writeFileSync(tmpFile, sql);
  try {
    execSync(
      `npx wrangler d1 execute ${db} --remote --command "$(cat ${tmpFile})"`,
      { encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024, timeout: 30000, stdio: 'pipe' }
    );
    return true;
  } catch (error: any) {
    log(`D1 exec failed: ${error.message}`);
    return false;
  }
}

function escSQL(s: string | null | undefined): string {
  if (s === null || s === undefined) return 'NULL';
  return `'${s.replace(/'/g, "''")}'`;
}

async function main() {
  log('='.repeat(60));
  log(`SEO Sync: ${SOURCE_DB} → ${TARGET_DB}${DRY_RUN ? ' (DRY RUN)' : ''}`);
  log('='.repeat(60));

  // Fetch SEO data from source
  log('Fetching SEO data from migration DB...');
  const products = queryD1(SOURCE_DB, `
    SELECT
      sku,
      seo_title,
      seo_meta_description,
      seo_og_title,
      seo_og_description,
      seo_keywords,
      seo_faqs,
      seo_use_cases,
      gmc_google_category,
      gmc_product_type,
      gmc_custom_label_0,
      gmc_custom_label_1,
      seo_last_optimized
    FROM storefront_products
    WHERE seo_title IS NOT NULL
  `) as SEOProduct[];

  log(`Found ${products.length} products with SEO data`);

  if (products.length === 0) {
    log('No SEO data to sync.');
    return;
  }

  let success = 0;
  let failed = 0;
  let notFound = 0;

  for (let i = 0; i < products.length; i++) {
    const p = products[i];
    const progress = `[${i + 1}/${products.length}]`;

    if (DRY_RUN) {
      log(`${progress} Would update: ${p.sku} - ${p.seo_title?.substring(0, 50)}...`);
      success++;
      continue;
    }

    const sql = `UPDATE products SET
      seo_title = ${escSQL(p.seo_title)},
      seo_meta_description = ${escSQL(p.seo_meta_description)},
      seo_og_title = ${escSQL(p.seo_og_title)},
      seo_og_description = ${escSQL(p.seo_og_description)},
      seo_keywords = ${escSQL(p.seo_keywords)},
      seo_faqs = ${escSQL(p.seo_faqs)},
      seo_use_cases = ${escSQL(p.seo_use_cases)},
      gmc_google_category = ${escSQL(p.gmc_google_category)},
      gmc_product_type = ${escSQL(p.gmc_product_type)},
      gmc_custom_label_0 = ${escSQL(p.gmc_custom_label_0)},
      gmc_custom_label_1 = ${escSQL(p.gmc_custom_label_1)},
      seo_last_optimized = ${escSQL(p.seo_last_optimized)}
    WHERE sku = ${escSQL(p.sku)}`;

    if (execD1(TARGET_DB, sql)) {
      log(`${progress} ✓ ${p.sku}`);
      success++;
    } else {
      log(`${progress} ✗ ${p.sku} - update failed`);
      failed++;
    }

    // Small delay to avoid rate limits
    if (i % 50 === 0 && i > 0) {
      await new Promise(resolve => setTimeout(resolve, 500));
    }
  }

  log('');
  log('='.repeat(60));
  log('SYNC COMPLETE');
  log('='.repeat(60));
  log(`Total: ${products.length}`);
  log(`Success: ${success}`);
  log(`Failed: ${failed}`);
  log(`Not found in target: ${notFound}`);
}

main().catch(e => {
  console.error('Fatal error:', e);
  process.exit(1);
});
